### ISSUE TITLE
As a student, you cannot change between mobile app - app inventor and mobile app- thunkable for submission type 

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4170]
When you select either app inventor or thunkable as your submission type and then go back to update to the other submission type (thunkable to app inventor or app inventor to thunkable) your project is not updated. The only workaround right now is to select "other" or switch to an AI project, save, and then you can select the thunkable/app inventor. Verified locally and on QA

**Comment by dboyer** [comment]
I'm seeing the same issue on QA

**Comment by viviancan** [comment]
The switch should work now on QA, however some of the other platform switches are still kind of weird. I think this should be addressed and is logged in #4881

**Comment by dboyer** [comment]
Tested on QA and I'm seeing the same problem still:

- Set my coding type as App Inventor and upload a zip file. Both coding language and technical additions are green check marks
- Went back to coding type and changed it to Thunkable and added my project details page
- Clicked Save but the changes wouldn't save

@viviancan Screen capture of the [issue here](https://drive.google.com/file/d/1_VQ5mEMjqN6V4AgRRip_ptPaS4HHkvBb/view?usp=drivesdk).

**Comment by viviancan** [comment]
Pulling this back to in progress

**Comment by viviancan** [comment]
@dboyer This is on QA. I did something weird with the original PR and the actual code bug fix was not on QA 🤦‍♀️ It should work as expected for app inventor/thunkable

**Comment by dboyer** [comment]
Tested on QA and confirmed:

- Had the coding language set to Thunkable and was able to switch to App Inventor and then upload a file
- Had the coding language set to App Inventor and was able to switch to Thunkable. The uploaded file disappeared and I had to enter a Thunkable link
- The green check marks in coding language and technical additions worked as expected
